apiVersion: apps/v1
kind: Deployment
metadata:
  name: insights-service
  labels:
    app: insights-service
    app.kubernetes.io/component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insights-service
  template:
    metadata:
      labels:
        app: insights-service
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: app
          image: yaseenas/insights-service:latest
          ports:
            - containerPort: 3004
              name: http
          workingDir: /app/services/insights-service
          envFrom:
            - configMapRef:
                name: insights-service-config
          readinessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 30
            periodSeconds: 15
