apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  SERVICE_NAME: notification-service
  PORT: "3008"
  WS_PORT: "3018"
  NODE_ENV: production
  DB_HOST: postgres-service.database.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: asset_management
  DB_USER: admin
  DB_PASSWORD: admin123
  REDIS_HOST: redis-service
  REDIS_PORT: "6379"
  SMTP_HOST: smtp.mailtrap.io
  SMTP_PORT: "587"
