apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
    app.kubernetes.io/component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: app
          image: yaseenas/notification-service:latest
          ports:
            - containerPort: 3008
              name: http
            - containerPort: 3018
              name: websocket
          workingDir: /app/services/notification-service
          envFrom:
            - configMapRef:
                name: notification-service-config
            - secretRef:
                name: notification-service-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 3008
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3008
            initialDelaySeconds: 30
            periodSeconds: 15
