apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - name: http
      port: 80
      targetPort: 3008
    - name: websocket
      port: 3018
      targetPort: 3018
  type: ClusterIP
