apiVersion: v1
kind: ConfigMap
metadata:
  name: trading-service-config
data:
  SERVICE_NAME: trading-service
  PORT: "3003"
  NODE_ENV: production
  DB_HOST: postgres-service.database.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: trading_db
  ENGAGEMENT_DB_NAME: engagement_db
  AUTH_DB_NAME: auth_db
  DB_USER: admin
  REDIS_URL: redis://redis-service:6379
  INSIGHTS_SERVICE_URL: http://insights-service
  UPSTOX_REDIRECT_URI: http://api-gateway/v1/broker/callback/upstox
  OTP_PROVIDER: mock
