apiVersion: v1
kind: ConfigMap
metadata:
  name: trading-service-config
data:
  SERVICE_NAME: trading-service
  PORT: "3003"
  NODE_ENV: production
  DB_HOST: postgres-service.database.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: trading_db
  DB_USER: admin
  REDIS_URL: redis://redis-service:6379
  AUTH_SERVICE_URL: http://auth-service
  MARKET_SERVICE_URL: http://market-service
  UPSTOX_REDIRECT_URI: http://api-gateway/v1/broker/callback/upstox
