apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-service
  labels:
    app: trading-service
    app.kubernetes.io/component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trading-service
  template:
    metadata:
      labels:
        app: trading-service
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: app
          image: yaseenas/trading-service:latest
          ports:
            - containerPort: 3003
          workingDir: /app/services/trading-service
          envFrom:
            - configMapRef:
                name: trading-service-config
            - secretRef:
                name: trading-service-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 30
            periodSeconds: 15
