apiVersion: apps/v1
kind: Deployment
metadata:
  name: engagement-service
  labels:
    app: engagement-service
    app.kubernetes.io/component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: engagement-service
  template:
    metadata:
      labels:
        app: engagement-service
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: app
          image: yaseenas/engagement-service:latest
          ports:
            - containerPort: 3007
            - containerPort: 3018
          workingDir: /app/services/engagement-service
          envFrom:
            - configMapRef:
                name: engagement-service-config
          readinessProbe:
            httpGet:
              path: /health
              port: 3007
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3007
            initialDelaySeconds: 30
            periodSeconds: 15
