apiVersion: v1
kind: Service
metadata:
  name: backtest-service
  labels:
    app: backtest-service
spec:
  selector:
    app: backtest-service
  ports:
    - port: 80
      targetPort: {{ .Values.backtestService.port }}
