apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.postgresql.namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgresql.credentials.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.credentials.password | quote }}
  POSTGRES_DB: {{ .Values.postgresql.credentials.database | quote }}
