apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: {{ .Values.postgresql.namespace }}
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
