{{- if .Values.jenkins.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: {{ .Values.jenkins.namespace }}
  labels:
    app: jenkins
    environment: {{ .Values.global.environment }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-sa
      containers:
        - name: jenkins
          image: {{ .Values.jenkins.image }}
          securityContext:
            privileged: true
          ports:
            - containerPort: 8080
            - containerPort: 50000
          volumeMounts:
            - name: jenkins-storage
              mountPath: /var/jenkins_home
            - name: docker-sock
              mountPath: /var/run/docker.sock
      volumes:
        - name: jenkins-storage
          persistentVolumeClaim:
            claimName: jenkins-pvc
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
{{- end }}
