apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  labels:
    app: recommendation-service
spec:
  selector:
    app: recommendation-service
  ports:
    - port: 80
      targetPort: {{ .Values.recommendationService.port }}
