apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-service
  labels:
    app: recommendation-service
    app.kubernetes.io/component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recommendation-service
  template:
    metadata:
      labels:
        app: recommendation-service
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: app
          image: yaseenas/recommendation-service:latest
          ports:
            - containerPort: 3006
          workingDir: /app/services/recommendation-service
          envFrom:
            - configMapRef:
                name: recommendation-service-config
          readinessProbe:
            httpGet:
              path: /health
              port: 3006
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3006
            initialDelaySeconds: 30
            periodSeconds: 15
